apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-config
  namespace: argocd
spec:
  encryptedData:
    privateKey: AgAjMkXsBPaTCLkODMvshXZyheMcgcisyOvxM74F8J+7SpB9boezsgIVkdZTA1uKj2mT/VwQUi94crNcwhE/Jmy0SRnxC4u0T9sKNrllPuD8oMxOyBqARz9VMI5onMHJUNiui/Ma2IsWA94iXPp3NtYdYiFvNTvD3kBNpZ9BUM7XT+qZsaDYoIOHPi407N7HQSbAz6CEV2k5QHBNJEm1HkLC/k6SGEpUGlrlNi5wKJlc5ttMYoycqUvnSaJTWl7U0+sJjRjsMAx2O4nXMdTrBKzPdFQka11fdC2VcnW1dU+wox9qeo/W/1v0YvRudAmqTQkun/sW3eQbmaaANlDCZd38hgm2trHEfJqBKuVy/2hexw4pIxKRiED438xqhOkyBovC0wAfCSI9kMCcRh+BjPP+3XKUK7BnRxY83JT4o8LKmgnBwpAgg0dfAlAbxyTfacnt4yYQXYfnBUqJQ25PN3+sE29j719OUI8N2XRD/hT+MHSFYVhGUSFi0m2V3Hli/NkuoryPp/yuOmlffZbQ6UqVaSqsJoNBs/4xgqTMkidFBZl8vNdJb+qWcuy/vMcUsyFUpg42epAr/Pdm0ZPT97EQ5ZLAUOZM8XO5HIgMpn9slaf9nFSTOQhzAhfAZcbn/1aZvTdWShogEboGb6ZsPbgX/miY6i/IjPmacyTNI7rdOENUO8orwQsaQ+syd0mEtaFLBnPHzpy2ZYEdWo41nZIJPN4v9XS3AgE7YYuwjvN9ccll4S+nxFR5jvISGJYekkn64xiHogxb+7XAlQQe3lB9/O3W9+c5sD5t/vMWv2Cdd68Xkh5ekR/E0vtIWVVeATovzlmh++MIeYp4N+2OXgfPteiE1g5YEmqlTcyrXZKWfbKvk1C12q54mvdeQp5jtAvkLZ+J4AylnIY5A+NCYLJjf/fEIxbRta0vCF+BoiKxpMFDq3nSpDadKLBhPwMObLO8y1JSqvNpO3RmZVN73bPGvfdRvqq9kjK05yJU85MEUBzVtejagabttG3hNF2rxYpdVJImQvSyix4gcJlSETAg2Mdh9z65iwi/VK17C7pWkIUsBzW0uRBrAkHSI1WS95P0D9/uOz2F+DBV9Fi2edYquUHru1/vC039RDbykkU+pN+rOeXIv6BJU5MpOX7zLRktktn/6OvRGeY8RRPfpouaHw8s07bDXRxhYNmFx5st013ko10YVqfcM3EFo230ec2FtIgG14d8AKuRY69s0kBu0F1wm0RhzMYMg1wzIFaNaquUkCypRW9a9VjKR+eDl5N2+ELjC6oM066qbfLjJ+wK7fHpgY7iXdOMXXbL2UBlq7z46GJUOcbNcpcKsMuQPD7BHaXyZ6nArWXC/6XtgNqyupegTwrEJdABfz+MhMU6+In3m7dUkQPvLbslX9qI+PAVuh7a
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-config
      namespace: argocd

